default_platform(:android)

platform :android do

  before_all do
    ENV["FIREBASE_LOGIN_CREDENTIALS"] = "fastlane/firebase_login_credentials.json"
    ENV["FIREBASE_APP_ID"] = "1:111111111111:android:222222222"
  end

   ######## FIREBASE DISTRIBUTION  ########
  desc "Submit a new Google Test Build to Firebase App Distribution"
  lane :testGoogle do |options|
     gradle(task: "clean")
     gradle(task: "assemble", flavor: "Google", build_type: "Debug")

      # find apk path
     output_path = "./app/build/outputs/apk/google/debug/"
     output_json_path = output_path + "output-metadata.json"
     build_output = load_json(json_path: output_json_path)
     elements = build_output["elements"][0]
     apk_path = output_path + elements["outputFile"]

     release_note_information = " BRANCH => #{git_branch} - developer: #{last_git_commit[:author]}"
     release_note = "#{release_note_information} \n #{options[:r]}"

     firebase_app_distribution(
           app: ENV["FIREBASE_APP_ID"],
           apk_path: apk_path,
           release_notes: "#{release_note}",
           groups_file: "fastlane/groups.txt",
           service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"]
     )
     # fastlane testGoogle r:"First Alpha Release"
  end

end