
name: Distribute

on:
  push:
    branches: [ test ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.3'

      - name: Install Bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Create Firebase Service Credentials file
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json
        env:
          FIREBASE_CREDENTIALS: ${{ FIREBASE_CREDENTIALS }}

      - name: Distribute app with 🔥 App Distribution 🚀
          run: bundle exec fastlane distribute
          env:
            FIREBASE_APP_ID: ${{ FIREBASE_APP_ID }}