name: Distribute

on:
  push:
    branches: [ test ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install Bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3


      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane distribute
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}